### ISSUE TITLE
Diseño: Tours nacionales

### ISSUE THREAD

**Issue by rafaelborjadev** [rafaelborjadev/lic-catedra#15]
Grid para mostrar los viajes disponibles y vistas de detalle

**Comment by LuisVillalta3** [comment]
![iPhone 14 Plus - 3](https://user-images.githubusercontent.com/50143567/201431197-716984dc-5094-4ae2-ab17-6d28393a5e25.jpg)
![Tour nacional](https://user-images.githubusercontent.com/50143567/201431233-e8cae1ef-55f0-44a2-a8d5-6b5e1ea6cb37.jpg)
