### ISSUE TITLE
Diseño: Nosotros

### ISSUE THREAD

**Issue by rafaelborjadev** [rafaelborjadev/lic-catedra#6]
Historia de la empresa, misión, visión y fotos.

- Propuesta: Mismo slider de la página principal con el staff

**Comment by LuisVillalta3** [comment]
Designs:
![NOSOTROS](https://user-images.githubusercontent.com/50143567/200967475-a91873c8-5a45-4e01-b271-5447688974eb.jpg)


![iPhone 14 Plus - 1](https://user-images.githubusercontent.com/50143567/200967431-ebde2f57-67cb-4b31-996a-5646fb17cd8d.jpg)
