### ISSUE TITLE
Diseño: Contacto

### ISSUE THREAD

**Issue by rafaelborjadev** [rafaelborjadev/lic-catedra#7]
Formulario genérico para recibir información/asistencia de parte de la empresa.

**Comment by LuisVillalta3** [comment]
Designs:

![iPhone 14 Plus - 2](https://user-images.githubusercontent.com/50143567/200967284-b204fe50-265c-43f0-bce0-2a1391345500.jpg)
![Contacto](https://user-images.githubusercontent.com/50143567/200967289-fa1e5023-5748-4fea-93cd-e28ae1b49384.jpg)
